databases:
  - name: valhalla-db
    plan: free

services:
  # 1. Redis Cache
  - type: redis
    name: valhalla-redis
    plan: free
    ipAllowList: []

  # 2. Microservices (Backend)
  - type: web
    name: valhalla-auth
    env: docker
    dockerContext: .
    dockerfilePath: auth-service/Dockerfile
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: valhalla-db
          property: connectionString
      - key: DB_NAME
        value: postgres
      - key: SERVICE_TOKEN
        generateValue: true

  - type: web
    name: valhalla-menu
    env: docker
    dockerContext: .
    dockerfilePath: menu-service/Dockerfile
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: valhalla-db
          property: connectionString
      - key: REDIS_HOST
        fromRedis:
          name: valhalla-redis
          property: host

  - type: web
    name: valhalla-order
    env: docker
    dockerContext: .
    dockerfilePath: order-service/Dockerfile
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: valhalla-db
          property: connectionString
      - key: RABBITMQ_HOST
        sync: false
      - key: SERVICE_TOKEN
        fromService:
          type: web
          name: valhalla-auth
          envVar: SERVICE_TOKEN

  - type: web
    name: valhalla-inventory
    env: docker
    dockerContext: .
    dockerfilePath: inventory-service/Dockerfile
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: valhalla-db
          property: connectionString

  - type: web
    name: valhalla-payment
    env: docker
    dockerContext: .
    dockerfilePath: payment-service/Dockerfile
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: valhalla-db
          property: connectionString

  - type: web
    name: valhalla-analytics
    env: docker
    dockerContext: .
    dockerfilePath: analytics-service/Dockerfile
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: valhalla-db
          property: connectionString
      - key: RABBITMQ_HOST
        sync: false

  # 3. API Gateway (Nginx)
  - type: web
    name: valhalla-gateway
    env: docker
    dockerContext: .
    dockerfilePath: gateway/Dockerfile
    plan: free
    envVars:
      - key: FRONTEND_ORIGIN
        value: https://valhalla-suite.onrender.com

  # 4. Frontend (Next.js)
  - type: web
    name: valhalla-frontend
    env: docker
    dockerContext: .
    dockerfilePath: frontend/Dockerfile
    plan: free
    envVars:
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: valhalla-gateway
          property: host
