"""test auth migration

Revision ID: 6ac005909c5c
Revises: 2f8b1a399196
Create Date: 2026-02-20 14:04:18.845746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ac005909c5c'
down_revision: Union[str, Sequence[str], None] = '2f8b1a399196'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('test_migration_flag', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'test_migration_flag')
    # ### end Alembic commands ###
