"""add test_migration_flag

Revision ID: 223d785689bd
Revises: 72205c5e0154
Create Date: 2026-02-20 07:41:45.203768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '223d785689bd'
down_revision: Union[str, Sequence[str], None] = '72205c5e0154'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_items', sa.Column('test_migration_flag', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_items', 'test_migration_flag')
    # ### end Alembic commands ###
